name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --release

      - name: Unit tests
        run: cargo test --verbose

      - name: Install ajv-cli
        run: npm install -g ajv-cli@5

      - name: Validate JSON examples
        run: |
          ajv validate -s schemas/proof.schema.json -d docs/data/proof_with_cut.json
          ajv validate -s schemas/proof.schema.json -d docs/data/proof_cut_eliminated.json
      - name: Demo pipeline check
        run: |
          # BEFORE should contain a Cut
          grep -q '"rule":"Cut"' docs/data/proof_with_cut.json

          # AFTER should NOT contain a Cut
          ! grep -q '"rule":"Cut"' docs/data/proof_cut_eliminated.json

          # Simple fragility metric = count nodes
          before_nodes=$(jq '.nodes | length' docs/data/proof_with_cut.json)
          after_nodes=$(jq '.nodes | length' docs/data/proof_cut_eliminated.json)

          echo "Nodes before=$before_nodes after=$after_nodes"
          if [ "$after_nodes" -ge "$before_nodes" ]; then
            echo "Fragility did not drop" && exit 1
          fi
