name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate JSON examples
        run: |
          ajv validate -s schemas/proof.schema.json -d examples/proof_with_cut.json
          ajv validate -s schemas/proof.schema.json -d examples/proof_cut_eliminated.json
          ajv validate -s schemas/registry.schema.json -d examples/R.json
